import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ConnectorProvider } from "./connector";
import { Sidebar } from "./sidebar";
import "./globals.css";

const poppins = Poppins({
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConnectorProvider>
      <html lang="en">
        <body
          className={`${poppins.className} h-screen bg-background text-foreground flex`}
        >
          <Sidebar />
          <main className="p-4 flex-1">{children}</main>
        </body>
      </html>
    </ConnectorProvider>
  );
}
